
export enum TaskStatus {
    PLANNING = 'planning',
    BACKLOG = 'backlog',
    NOT_STARTED = 'not-started',
    DEVELOPMENT = 'development',
    REVIEW = 'review',
    NIGHTLY = 'nightly',
    STAGING = 'staging',
    PRODUCTION = 'production',
    DEPRECATED = 'deprecated',
}

export interface Entity {
    // for mock data.  Will use firebase generated id when be is implemented
    // this id is generated by the in memory web api genId method
    id?: number;
    displayName: string;
}

export interface Task extends Entity {
    // entityId: string;
    // displayName: string;
    description: string;

    // change to string when firebase implemented
    boardId?: number;
    subTasks: string[];
    status: TaskStatus | string;
}

export interface Board extends Entity {
    // for mock data.  Will use firebase generated id when be is implemented
    // entityId: string;
    // displayName: string;
    status: TaskStatus | string;
    // tasks: string[];
    tasks?: Task[];
}

export enum FormMode {
    CREATE = 'create',
    EDIT = 'edit',
}

export interface SortedTasks {
    [key: string]: Task[];
}

export interface ColumnOrder {
    [key: string]: number;
}

export interface ColumnColor {
    [key: string]: string;
}